name: Continuous Integration

on:
  push:
    branches:
      - main # Change this to the default branch name of your repository
  pull_request:
    branches:
      - main # Change this to the default branch name of

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x # Change this to the desired Node.js version

      - name: Install dependencies
        run: npm install
